### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shubham6697**
Hello Vivek , I make some changes in this repository please merge my pull request.

### CODE REVIEW

**Comment by Shubham6697** [comment]
Yeh wla kr

**Comment by ekmavivek-1729** [comment]
Hello Shubham..

**Comment by ekmavivek-1729** [comment]
Good job

**Comment by Shubham6697** [comment]
Waah yaar

**Comment by Shubham6697** [comment]
Yeh toh mast chizz hai

**Pull request merged**
